### PR TITLE
Python3 support

### LINKED ISSUE #1: celery-dyrygent appears to only support python 2.x
This is the stack trace i get when attempting to run a workflow. I do not believe it's necessary to include more code, but i can if you think it's necessary.

```
celery-worker_1    | [2020-04-12 15:11:57,579: INFO/MainProcess] Received task: workflow-processor[e529f4d8-3a0c-4717-af8f-83fd32aaf1dd]
celery-worker_1    | [2020-04-12 15:11:57,609: ERROR/ForkPoolWorker-2] Task workflow-processor[e529f4d8-3a0c-4717-af8f-83fd32aaf1dd] raised unexpected: AttributeError("'dict' object has no attribute 'iteritems'")
celery-worker_1    | Traceback (most recent call last):
celery-worker_1    |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
celery-worker_1    |     R = retval = fun(*args, **kwargs)
celery-worker_1    |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
celery-worker_1    |     return self.run(*args, **kwargs)
celery-worker_1    |   File "/usr/local/lib/python3.7/site-packages/celery_dyrygent/tasks/processor.py", line 10, in workflow_processor
celery-worker_1    |     wf = Workflow.from_dict(workflow_dict)
celery-worker_1    |   File "/usr/local/lib/python3.7/site-packages/celery_dyrygent/workflows/workflow.py", line 529, in from_dict
celery-worker_1    |     for node_id, node_dict in workflow_dict['nodes'].iteritems()
celery-worker_1    | AttributeError: 'dict' object has no attribute 'iteritems'
```

### LINKED ISSUE #5: Release version 0.7.0
Python 3 support was recently added.
Please prepare new release with version 0.7.0

### PR DESCRIPTION
**Pull request by brabiega**

### CODE REVIEW

**Comment by brabiega** [comment]
There is 1 component test failing due to fix in celery
https://github.com/celery/celery/pull/5613

**Comment by brabiega** [comment]
Tested with celery 4.4.2
Python 3.6.9
Python 3.8.2
Python 2.7.17
Tests are passing
Also tested manually, tasks are processed by workflow processor

**Comment by brabiega** [comment]
@sadziu82 could you take a look? :)

**Review by sadziu82 — APPROVED** [review]

**Comment by kironk** [comment]
Thank you for this. It would be great if you could cut a release with Python 3 support.

**Pull request merged**
